### ISSUE TITLE
**AuthViewModel: problems with Hilt**

### ISSUE THREAD

**Issue by YaroslavSulyma** [philipplackner/SNPLC#1]
Hi, I'm using hilt 2.31.2-alpha and _@ViewModelInject_ is deprecated, so I should use _@HiltViewModel_, but faced with an error  "*. AuthRepository cannot be provided without an @Provides-annotated method". I tried to change AuthModule, I added @Binds annotation and change **object** into **abstract class**, but the problem isn't solved. https://github.com/YaroslavSulyma/TripApp/tree/YaroslavSulyma

**Comment by RowlandOti** [comment]
In AuthModule, you have to provide a binding to the concrete class, to link to the interface. you can do so like:

```
@module()
abstract class AuthModule {
    // Some bindings
    @Binds
    abstract fun bindAuthReposiirory(repository: DefaultAuthRepository): AuthRepository
   // More bindings
}
```

**Comment by YaroslavSulyma** [comment]
I did the same. Check my branch. I tried to remove @HiltViewModel annotation and everything worked, but this solution isn't for me. Maybe the problem in Hilt.
https://github.com/YaroslavSulyma/TripApp/blob/YaroslavSulyma/app/src/main/java/com/example/tripapp/di/AuthModule.kt

**Comment by YaroslavSulyma** [comment]
I found an issue. In new Hilt version we should use @HiltViewModel instead of @ViewModelInject, and in our module we also should use @InstallIn(ViewModelComponent::class) and @ViewModelScope
[](https://stackoverflow.com/questions/66044784/hiltviewmodel-cannot-create-an-instance-of-class)
